Fix up param and remove deprecations in collection_objects_controller_spec. 18 pre-existing errors unaffected.  Typical error message is: -e:1:in `<main>' ------------------ --- Caused by: --- NoMethodError:   undefined method `api_v1_image_url' for #<#<Class:0x007fcbec949778>:0x007fcbf2be5490>   ./app/views/collection_objects/show.json.jbuilder:10:in `block (3 levels) in _app_views_collection_objects_show_json_jbuilder__2042781976756356737_70256963826000'
ActionView::Template::Error: undefined method `api_v1_image_url' for #<#<Class:0x007fcbec949778>:0x007fcbf1f6c2e0>