Handle InvalidForeignKey exception cleanly in unify
Mostly by chatgpt.

InvalidForeignKey exception `e` doesn't have `e.record`, so we were raising:

```
A NoMethodError occurred in unify#unify:

  undefined method 'record' for an instance of ActiveRecord::InvalidForeignKey
  app/models/concerns/shared/unify.rb:180:in 'block in Shared::Unify#unify'

-------------------------------
Github link:
-------------------------------

  https://github.com/SpeciesFileGroup/taxonworks/blob/f84194da0/app/models/concerns/shared/unify.rb#L180
```