added todo's for cached values in non-bibtex source types - What should cached_author_string be for verbatim, and cached (full ref) be for author? authority_name and set_cached_values should really be required in all subclasses of classes of source, but I'm not sure how to do that. Once that is done, can we move the "before_save :set_cached_values" to Source? (Although the actual tests will have to remain in each of the various subclasses because the expected results will be slightly different depending on the type of source.)
Note - Content test is still failing
NoMethodError: undefined method `type' for nil:NilClass
       ./spec/models/content_spec.rb:84:in `block (4 levels) in <top (required)>'