Add full stack trace to exception notifications
BACKGROUND: Tracing a hard to find bug. We have lots of "undefined method `contains?' for #<String" at app/models/geographic_item.rb:1058:in `contains?', but when checking with:
```ruby
Georeference.all.map { |g| g.error_geographic_item&.geo_object.class }.uniq
```
I get:
```ruby
[NilClass, RGeo::Geographic::ProjectedPolygonImpl]
```
Need to know whether `contains?` actually is from `geographic_item.rb:1058` or it is somewhere deeper.